
@startuml
start
:Usuário envia o formulário (requisição API).;
:API valida a requisição;
if (JSON está formatado corretamente?) then (Não)
    :API retorna erro de formatação (400 Bad Request).;
elseif (Credenciais do usuário estão autenticadas?) then (Não)
    :API retorna erro de autenticação (401 Unauthorized).;
else (Sim)
    :API consulta os dados na tabela "estatisticas_jogador";
    :API estrutura os dados de estatisticas_jogador em formato JSON;
    :API retorna o JSON com os dados para o usuário (200 Ok).;
endif
stop
@enduml
