@startuml
class Player {
    - id: INTEGER
    - birthDate: VARCHAR(50)
    - nickname: String
    - shirtNumber: String
    - weight: String
    - height: String
    - name: String
    - position: String "(VARCHAR(1) no banco)"
    - age: NUMERIC

    + Player(): Player
    + getters(): Type
    + setters(Type): void
    + toString(): String
    + hashCode(): int
    + equals(Object): boolean
}

class Team {
    - id: INTEGER
    - state: String
    - fullName: String
    - abbreviation: String
    - yearFounded: Integer
    - city: String

    + Team(): Team
    + getters(): Type
    + setters(Type): void
    + toString(): String
    + hashCode(): int
    + equals(Object): boolean
}

class Game {
    - id: VARCHAR
    - matchup: String

    + Game(): Game
    + getters(): Type
    + setters(Type): void
    + toString(): String
    + hashCode(): int
    + equals(Object): boolean
}

class Season {
    - id: VARCHAR
    - year: Integer

    + Season(): Season
    + getters(): Type
    + setters(Type): void
    + toString(): String
    + hashCode(): int
    + equals(Object): boolean
}

class PlayerStatistics {
    - id: VARCHAR
    - steals: Integer
    - blocks: Integer
    - points: Integer
    - assistances: Integer
    - threePointShots: Integer
    - rebounds: Integer
    - perimeterBaskets: Integer
    - freeThrows: Integer

    + PlayerStatistics(): PlayerStatistics
    + getters(): Type
    + setters(Type): void
    + toString(): String
    + hashCode(): int
    + equals(Object): boolean
}

class TeamStatistics {
    - id: VARCHAR
    - steals: Integer
    - wl: String
    - blocks: Integer
    - points: Integer
    - threePointShots: Integer
    - rebounds: Integer
    - perimeterBaskets: Integer
    - freeThrows: Integer

    + TeamStatistics(): TeamStatistics
    + getters(): Type
    + setters(Type): void
    + toString(): String
    + hashCode(): int
    + equals(Object): boolean
}

interface Repository {
    + getAll(): List<Type>
    + save(Type): void
    + update(Type, Type): void
    + delete(Type): void
    + getById(Type): Type
}

abstract RepositoryImpl {
    + getAll(): List<Type>
    + save(Type): void
    + update(Type, Type): void
    + delete(Type): void
    + getById(Type): Type
}

class PlayerRepository {
    + getAll(): List<Player>
    + save(Player): void
    + update(UUID, Player): void
    + delete(UUID): void
    + getById(UUID): Player
}

class TeamRepository {
    + getAll(): List<Team>
    + save(Team): void
    + update(UUID, Team): void
    + delete(UUID): void
    + getById(UUID): Team
}

class GameRepository {
    + getAll(): List<Game>
    + save(Game): void
    + update(UUID, Game): void
    + delete(UUID): void
    + getById(UUID): Game
}

class SeasonRepository {
    + getAll(): List<Season>
    + save(Season): void
    + update(UUID, Season): void
    + delete(UUID): void
    + getById(UUID): Season
}

class PlayerStatisticsRepository {
    + getAll(): List<PlayerStatistics>
    + save(PlayerStatistics): void
    + update(UUID, PlayerStatistics): void
    + delete(UUID): void
    + getById(UUID): PlayerStatistics
}

class TeamStatisticsRepository {
    + getAll(): List<TeamStatistics>
    + save(TeamStatistics): void
    + update(UUID, TeamStatistics): void
    + delete(UUID): void
    + getById(UUID): TeamStatistics
}

Repository <|.. RepositoryImpl
RepositoryImpl <|-- PlayerRepository
RepositoryImpl <|-- TeamRepository
RepositoryImpl <|-- GameRepository
RepositoryImpl <|-- SeasonRepository
RepositoryImpl <|-- PlayerStatisticsRepository
RepositoryImpl <|-- TeamStatisticsRepository

PlayerRepository ..> Player
TeamRepository ..> Team
GameRepository ..> Game
SeasonRepository ..> Season
PlayerStatisticsRepository ..> PlayerStatistics
TeamStatisticsRepository ..> TeamStatistics

Player o-- Team : pertence_a
Team *-- TeamStatistics : tem
Team *-- Game : joga
Player *-- PlayerStatistics : tem
PlayerStatistics *-- Game : ocorre_em
TeamStatistics *-- Game : ocorre_em
Game *-- Team : home
Game *-- Team : away
Game *-- Team : winner
Game *-- Season : faz_parte_de
@enduml
