@startuml
class Player {
    - id: String
    - birthDate: Date
    - nickname: String
    - shirtNumber: Integer
    - weight: Double
    - height: Integer
    - name: String
    - position: String
    - age: Integer

    + Player(): Player
    + getters(): Type
    + setters(Type): void
    + toString(): String
    + hashCode(): int
    + equals(Object): boolean
}

class Team {
    - id: String
    - state: String
    - fullName: String
    - abbreviation: String
    - yearFounded: Date
    - city: String

    + Team(): Team
    + getters(): Type
    + setters(Type): void
    + toString(): String
    + hashCode(): int
    + equals(Object): boolean
}

class Game {
    - id: String
    - matchup: String

    + Game(): Game
    + getters(): Type
    + setters(Type): void
    + toString(): String
    + hashCode(): int
    + equals(Object): boolean
}

class Season {
    - id: String
    - year: Date

    + Season(): Season
    + getters(): Type
    + setters(Type): void
    + toString(): String
    + hashCode(): int
    + equals(Object): boolean
}

class PlayerStatistics {
    - id: String
    - steals: Integer
    - blocks: Integer
    - points: Integer
    - assistances: Integer
    - threePointShots: Integer
    - rebounds: Integer
    - perimeterBaskets: Integer
    - freeThrows: Integer

    + PlayerStatistics(): PlayerStatistics
    + getters(): Type
    + setters(Type): void
    + toString(): String
    + hashCode(): int
    + equals(Object): boolean
}

class TeamStatistics {
    - id: String
    - steals: Integer
    - wl: String
    - blocks: Integer
    - points: Integer
    - threePointShots: Integer
    - rebounds: Integer
    - perimeterBaskets: Integer
    - freeThrows: Integer

    + TeamStatistics(): TeamStatistics
    + getters(): Type
    + setters(Type): void
    + toString(): String
    + hashCode(): int
    + equals(Object): boolean
}

interface Repository {
    + getAll(): List<Type>
    + save(Type): void
    + update(Type, Type): void
    + delete(Type): void
    + getById(Type): Type
}

abstract RepositoryImpl {
    + getAll(): List<Type>
    + save(Type): void
    + update(Type, Type): void
    + delete(Type): void
    + getById(Type): Type
}

class PlayerRepository {
    + getAll(): List<Player>
    + save(Player): void
    + update(String, Player): void
    + delete(String): void
    + getById(String): Player
}

class TeamRepository {
    + getAll(): List<Team>
    + save(Team): void
    + update(String, Team): void
    + delete(String): void
    + getById(String): Team
}

class GameRepository {
    + getAll(): List<Game>
    + save(Game): void
    + update(String, Game): void
    + delete(String): void
    + getById(String): Game
}

class SeasonRepository {
    + getAll(): List<Season>
    + save(Season): void
    + update(String, Season): void
    + delete(String): void
    + getById(String): Season
}

class PlayerStatisticsRepository {
    + getAll(): List<PlayerStatistics>
    + save(PlayerStatistics): void
    + update(String, PlayerStatistics): void
    + delete(String): void
    + getById(String): PlayerStatistics
}

class TeamStatisticsRepository {
    + getAll(): List<TeamStatistics>
    + save(TeamStatistics): void
    + update(String, TeamStatistics): void
    + delete(String): void
    + getById(String): TeamStatistics
}

Repository <|.. RepositoryImpl
RepositoryImpl <|-- PlayerRepository
RepositoryImpl <|-- TeamRepository
RepositoryImpl <|-- GameRepository
RepositoryImpl <|-- SeasonRepository
RepositoryImpl <|-- PlayerStatisticsRepository
RepositoryImpl <|-- TeamStatisticsRepository

PlayerRepository ..> Player
TeamRepository ..> Team
GameRepository ..> Game
SeasonRepository ..> Season
PlayerStatisticsRepository ..> PlayerStatistics
TeamStatisticsRepository ..> TeamStatistics

Player o-- Team : pertence_a
Team *-- TeamStatistics : tem
Team *-- Game : joga
Player *-- PlayerStatistics : tem
PlayerStatistics *-- Game : ocorre_em
TeamStatistics *-- Game : ocorre_em
Game *-- Team : home
Game *-- Team : away
Game *-- Team : winner
Game *-- Season : faz_parte_de
@enduml
