@startuml
start
:Usuário envia o formulário (requisição API).;
:API valida a requisição;
if () then ([JSON está formatado corretamente.])
    if () then ([Credenciais do usuário estão autenticadas.])
        if () then([Dados obrigatórios são válidos])
            :API insere os dados na tabela "times" do banco de dados;
            if () then ([Inserção bem-sucedida.])
                :API retorna sucesso (201 Created) com detalhes do registro criado.;
            else ([Inserção mal-sucedida.])
                :API retorna erro interno (500 Internal Server Error).;
            endif
        else ([Dados obrigatórios não são válidos])
            :API retorna erro de validação (422 Unprocessable Entity).;
        endif
    else ([Credenciais do usuário não estão autenticadas.])
        :API retorna erro de autenticação (401 Unauthorized).;
    endif
else ([JSON não está formatado corretamente.])
    :API retorna erro de formatação (400 Bad Request).;
endif
stop
@enduml

