version: '3'
services:
  postgres:
    container_name: nba_api
    image: postgres:17
    environment:
      POSTGRES_USER: nba_api
      POSTGRES_PASSWORD: nbaapi
      POSTGRES_DB: nba_api
    #volumes:
    #  - postgres-data:/var/lib/postgresql/data
    ports:
      - "5666:5432"
    restart: unless-stopped

#volumes:
#  postgres-data: